deployment:
  repository: "github.com/nidhi-singh02/CrocSwap-protocol"  # give repo name if there are submodules, else give the folder till contracts
  contracts_path: ""  # give the path till contracts, if the repository is the contract folder itself, then leave it empty
  script_path: "misc/scripts/deploy.ts"  # this must be relative to the repository path + contracts_path(if applicable)
  network: "bartio"
  wallet:
    type: "private_key"  # currently only private_key wallet is supported. Do not change the type.
    value: "0x"
  dependency:
    type: local
    path: "dependency.sh"

    ## Full path for local dependency